vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    annonces:
      uri_prefix: /public/images/annonces
      upload_destination: "%kernel.project_dir%/public/images/annonces"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer